### ISSUE TITLE
NMAKE : fatal error U1052: file 'ms\nt.mak' not found

### ISSUE THREAD

**Issue by Thewbi** [conan-community/conan-openssl#40]
Hi,

I am on windows 10, Visual Studio 2012 (vc110). I want to use the 32-bit versions of the POCO libraries. The build fails at the OpenSSL package, so to isolate the error, I now try to build the 32-bit libraries of OpenSSL only, which also fails.

Conan version: Conan version 0.29.2

my conanfile.txt
```
[requires]
#Poco/1.7.8p3@pocoproject/stable
#Boost/1.64.0@conan/stable
OpenSSL/1.0.2l@conan/stable

[generators]
cmake
```
When I execute 
```
conan install .. -s build_type=Debug -s arch=x86 --build missing
```

I eventually get 
```
...
OpenSSL/1.0.2l@conan/stable: WARN: Build folder C:\Users\wbi\.conan\data\OpenSSL\1.0.2l\conan\stable\build\aade09af893b263731251253842d2ccf0d0f70cf
ERROR: OpenSSL/1.0.2l@conan/stable: Error in build() method, line 107
        self.visual_build(config_options_string)
while calling 'visual_build', line 298
        self.run_in_src("%s && %s" % (vcvars, make_command))
while calling 'run_in_src', line 121
        self.run(command)
        ConanException: Error 2 while executing echo Conan:vcvars already set && nmake -f ms\nt.mak
```
When I manually execute:
```
"C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\../../VC/vcvarsall.bat" x86 && nmake -f ms\nt.mak
```
I get
```
Microsoft (R) Program Maintenance Utility Version 11.00.50727.1
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'ms\nt.mak' not found
Stop.
```

I found https://github.com/curl/curl/issues/1002
Maybe that is related.

If you need more info, please specify in small steps for a dumb person, because I do not have any experience with complicated C++ build tools!

Thank you for looking at this report.

**Comment by lasote** [comment]
The related issue is talking about the OpenSSL 1.1.0 branch, for 1.0.2 it should work ok. I've tried to build the x86 binaries and it's working, but I don't have Visual Studio 11, I don't know if it can be related. Please, try with `OpenSSL/1.0.2m@conan/stable` and post the result.

**Comment by lasote** [comment]
Hi, I've installed the visual 12. All built correctly, 1.0.2m

**Comment by Thewbi** [comment]
Thanks for the help lasote, still no luck.

conanfile.txt

```
[requires]
#Poco/1.7.8p3@pocoproject/stable
#Boost/1.64.0@conan/stable
#OpenSSL/1.0.2l@conan/stable
OpenSSL/1.0.2m@conan/stable

[generators]
cmake
```

Error

```
OpenSSL/1.0.2m@conan/stable:
OpenSSL/1.0.2m@conan/stable: ERROR: Package 'aade09af893b263731251253842d2ccf0d0f70cf' build failed
OpenSSL/1.0.2m@conan/stable: WARN: Build folder C:\Users\wbi\.conan\data\OpenSSL\1.0.2m\conan\stable\build\aade09af893b263731251253842d2ccf0d0f70cf
ERROR: OpenSSL/1.0.2m@conan/stable: Error in build() method, line 108
        self.visual_build(config_options_string)
while calling 'visual_build', line 299
        self.run_in_src("%s && %s" % (vcvars, make_command))
while calling 'run_in_src', line 122
        self.run(command)
        ConanException: Error 2 while executing call "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\../../VC/vcvarsall.bat" x86 && nmake -f ms\nt.mak
```

I am trying to check my setup but I am probably too much of a noob to sort this out :(
I think conan is a very great think and I hope I get it to work someday...

**Comment by lasote** [comment]
No idea why your compiler is complaining about that ``escape sequence``. I've followed exactly the same steps and works ok. Make sure you have the latest revision of the visual studio 11.0, it's the only thing that I can imagine...

**Comment by lasote** [comment]
We centralized the recipes we are creating in the **https://github.com/conan-community/community/issues** Please, open there the issue if still persist.
